name: Publish Package to GitHub NPM Registry

on:
  release:
    types: [published]
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: setup nodejs
          uses: actions/setup-node@v4
          with: 
            node-version: 20.x
            registry-url: 'https://npm.pkg.github.com/'
        - name: install dependencies
          run: npm install
        - name: Publish to GitHub Packages Registry
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

